version: "3.8"
services:
  frontend:
    image: git.trahan.dev/jtrahan/react-static:dev
    build:
      context: ./
    environment:
      NODE_ENV: development
    ports:
      - 3001:80
    networks:
      - ovnet1
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
  go-backend:
    image: git.trahan.dev/jtrahan/go-backend:dev
    build:
      context: ../backend/go-api/
      target: final
    ports:
      - 8283:8283
    networks:
      - ovnet1
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
networks:
  ovnet1:
    external: true
