version: '3'
services:
  frontend:
    build:
      context: ./frontend/
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    networks:
      - dockerdev
  go-backend:
    build:
      context: ./backend/go-api/
      target: final
    ports:
      - 8080:8080
    networks:
      - dockerdev
networks:
  dockerdev:
    driver: bridge


