version: "3.8"
services:
  frontend:
    image: git.trahan.dev/jtrahan/react-static:dev
    build:
      context: ./
    environment:
      NODE_ENV: production
    ports:
      - 3001:80
    networks:
      - ovnet1
  go-backend:
    image: git.trahan.dev/jtrahan/go-backend:dev
    build:
      context: ../backend/go-api/
      target: final
    ports:
      - 8280:8080
    networks:
      - ovnet1
networks:
  ovnet1:
    external: true
