version: '3.8'
services:
  haproxy:
    image: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "8404:8404"
    volumes:
      - ${HA_CONF_DIR-infrastructure/}:/usr/local/etc/haproxy
    networks:
      - ovnet0
      - ovnet1
      - ovnet2
    secrets:
     - haproxy_api.test.trahan.dev.pem
     - haproxy_test.justintrahan.com.pem
     - haproxy_test.trahan.dev.pem
  frontend:
    image: ${DOCKER_REGISTRY-jtrahan88/}calc-react-static:${DOCKER_IMG_TAG-v0.9.5-prod}
    build:
      context: ./frontend/
    environment:
      NODE_ENV: ${ENVIRON-development}
    ports:
      - 3001:80
    networks:
      - ovnet1
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
  go-backend:
    image: ${DOCKER_REGISTRY-jtrahan88/}go-backend:${DOCKER_IMG_TAG-v0.9.5-prod}
    build:
      context: ./backend/go-api/
      target: final
    ports:
      - 8283:8283
    networks:
      - ovnet2
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
networks:
  ovnet0:
    external: true
  ovnet1:
    external: true
  ovnet2:
    external: true
secrets:
  haproxy_api.test.trahan.dev.pem:
    external: true
  haproxy_test.justintrahan.com.pem:
    external: true
  haproxy_test.trahan.dev.pem:
    external: true