version: "3.9"
services:
  frontend:
    image: ${DOCKER_REGISTRY-jtrahan88/}calc-react-static:${DOCKER_IMG_TAG-dev}
    build:
      context: ./frontend/
      args:
        - BUILD_ENV
    environment:
      NODE_ENV: ${NODE_BUILD-development}
    ports:
      - 3001:80
    networks:
      - ovnet1
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
  go-backend:
    image: ${DOCKER_REGISTRY-jtrahan88/}calc-go-backend:${DOCKER_IMG_TAG-dev}
    build:
      context: ./backend/go-api/
      target: final
    ports:
      - 8283:8283
    networks:
      - ovnet1
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
networks:
  ovnet1:
    external: true
