version: '3'
services:
  haproxy:
    image: haproxy
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./infrastructure:/usr/local/etc/haproxy
    networks:
      - ovnet0
      - ovnet1
      - ovnet2
  frontend:
    image: react-static:${DOCKER_IMG_TAG-dev}
    build:
      context: ./frontend/
    environment:
      NODE_ENV: development
    ports:
      - 3001:80
    networks:
      - ovnet1
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
  go-backend:
    image: go-backend:${DOCKER_IMG_TAG-dev}
    build:
      context: ./backend/go-api/
      target: final
    ports:
      - 8283:8283
    networks:
      - ovnet2
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
networks:
  ovnet0:
    external: true
  ovnet1:
    external: true
  ovnet2:
    external: true