// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/compound-interest": {
            "post": {
                "description": "Takes params from frontend and returns YearlyTotals for Compound Interest",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calc"
                ],
                "summary": "Compund Interest calculation",
                "operationId": "auth-login",
                "parameters": [
                    {
                        "description": "Initial Asset Value",
                        "name": "initAmount",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "description": "Monthly contribution",
                        "name": "monthlyContribution",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "description": "Interest Rate used in calculation",
                        "name": "interestRate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "description": "Number of years to run calculation",
                        "name": "numberOfYearsbint",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.YearlyTotals"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.YearlyTotals": {
            "type": "object",
            "properties": {
                "contributions": {
                    "type": "number"
                },
                "gainfromint": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                },
                "yearlyIncome": {
                    "type": "number"
                },
                "yearlyInterest": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
