// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/compound-interest": {
            "post": {
                "description": "Takes params from frontend and returns YearlyTotals for Compound Interest",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calc"
                ],
                "summary": "Compund Interest calculation",
                "operationId": "Calculator",
                "parameters": [
                    {
                        "description": "Values from user",
                        "name": "InitialNumericInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.InitialNumericInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.YearlyTotals"
                        }
                    }
                }
            }
        },
        "/api/healthstats": {
            "get": {
                "description": "Retures Date/Time Server Hostname and Health status if API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HealthCheck"
                ],
                "summary": "Returns Server Health statuses",
                "operationId": "HealtchCheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hlthchk.ServerHealthStats"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hlthchk.ServerHealthStats": {
            "type": "object",
            "properties": {
                "currentDateTime": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "main.InitialNumericInput": {
            "type": "object",
            "properties": {
                "initAmount": {
                    "type": "number"
                },
                "interestRate": {
                    "type": "number"
                },
                "monthlyContribution": {
                    "type": "number"
                },
                "numberOfYears": {
                    "type": "integer"
                }
            }
        },
        "main.YearlyTotals": {
            "type": "object",
            "properties": {
                "yearlyContributions": {
                    "type": "number"
                },
                "yearlyTotalGains": {
                    "type": "number"
                },
                "total": {
                    "type": "number"
                },
                "year": {
                    "type": "integer"
                },
                "yearlyIncome": {
                    "type": "number"
                },
                "yearlyInterest": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
