definitions:
  hlthchk.ServerHealthStats:
    properties:
      currentDateTime:
        type: string
      hostname:
        type: string
      message:
        type: string
    type: object
  main.InitialNumericInput:
    properties:
      initAmount:
        type: number
      interestRate:
        type: number
      monthlyContribution:
        type: number
      numberOfYears:
        type: integer
    type: object
  main.YearlyTotals:
    properties:
      yearlyContributions:
        type: number
      yearlyTotalGains:
        type: number
      total:
        type: number
      year:
        type: integer
      yearlyIncome:
        type: number
      yearlyInterest:
        type: number
    type: object
info:
  contact: {}
paths:
  /api/compound-interest:
    post:
      consumes:
      - application/json
      description: Takes params from frontend and returns YearlyTotals for Compound
        Interest
      operationId: Calculator
      parameters:
      - description: Values from user
        in: body
        name: InitialNumericInput
        required: true
        schema:
          $ref: '#/definitions/main.InitialNumericInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.YearlyTotals'
      summary: Compund Interest calculation
      tags:
      - Calc
  /api/healthstats:
    get:
      description: Retures Date/Time Server Hostname and Health status if API.
      operationId: HealtchCheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hlthchk.ServerHealthStats'
      summary: Returns Server Health statuses
      tags:
      - HealthCheck
swagger: "2.0"
